import Head from 'next/head';
import Header from '../organisms/Header/Header';
import clsx from 'clsx';
import styles from './Layout.module.scss';

function Layout({ children }) {
	return (
		<>
			<Head>
				<title>NEXT Recipe</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={clsx(styles.main)}>
				<Header />
			</main>
			{children}
		</>
	);
}

export default Layout;
