import Head from 'next/head';
import styles from './Home.module.scss';
import clsx from 'clsx';
import axios from 'axios';
import Title from '@/components/atoms/text/Title';
import Text from '@/components/atoms/text/Text';
import { Pic } from '@/components/atoms/pic/Pic';

export default function Home({ meals }) {
	console.log(meals);
	// idMeal
	// strMeal
	// strMealThumb

	return (
		<>
			<Head>
				<title>NEXT Recipe</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={clsx(styles.main)}>
				<Text type={'breadcrumb'} tag={'span'} isOn={true}>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae, reprehenderit.
				</Text>
				<div className={clsx(styles.picFrame)}>
					<Pic imgSrc={meals[0].strMealThumb} />
				</div>
			</main>
		</>
	);
}

export async function getStaticProps() {
	const { data } = await axios.get('/filter.php?a=American');
	console.log('data fetching on Server', data);
	return {
		props: data,
		revalidate: 60 * 60 * 24,
	};
}
